base_url = "https://www.snoyman.com"
default_language = "en"
compile_sass = false
generate_feeds = true
feed_filenames = ["rss.xml"]
title = "Michael Snoyman's Homepage"
description = "Michael Snoyman's personal homepage and blog, featuring writing about programming, open source, health, finance, religion, and whatever else catches his interest."

taxonomies = [
  {name = "tags", paginate_by = 20, feed = true},
  {name = "series", paginate_by = 20, feed = true},
]

[markdown.highlighting]
theme = "solarized-light"

[extra]
# Put all your custom variables here
